fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    staging: "https://github.com/puppet-community/puppet-staging.git"
    wget: "https://github.com/maestrodev/puppet-wget.git"
  symlinks:
    logstash: "#{source_dir}"
